SensorViewConfiguration:
  version:
    - is_set:
  sensor_id:
    - is_set:
  mounting_position:
  mounting_position_rmse:
  field_of_view_horizontal:
  field_of_view_vertical:
  range:
    - is_greater_than_or_equal_to: 0
  update_cycle_time:
  update_cycle_offset:
  simulation_start_time:
  omit_static_information:
  generic_sensor_view_configuration:
  radar_sensor_view_configuration:
  lidar_sensor_view_configuration:
  camera_sensor_view_configuration:
  ultrasonic_sensor_view_configuration:
GenericSensorViewConfiguration:
  sensor_id:
  mounting_position:
  mounting_position_rmse:
  field_of_view_horizontal:
  field_of_view_vertical:
RadarSensorViewConfiguration:
  sensor_id:
  mounting_position:
  mounting_position_rmse:
  field_of_view_horizontal:
  field_of_view_vertical:
  number_of_rays_horizontal:
    - is_greater_than_or_equal_to: 1
  number_of_rays_vertical:
    - is_greater_than_or_equal_to: 1
  max_number_of_interactions:
    - is_greater_than_or_equal_to: 1
  emitter_frequency:
    - is_greater_than_or_equal_to: 0
  tx_antenna_diagram:
  rx_antenna_diagram:
  AntennaDiagramEntry:
    horizontal_angle:
    vertical_angle:
    response:
LidarSensorViewConfiguration:
  sensor_id:
  mounting_position:
  mounting_position_rmse:
  field_of_view_horizontal:
  field_of_view_vertical:
  number_of_rays_horizontal:
    - is_greater_than_or_equal_to: 1
  number_of_rays_vertical:
    - is_greater_than_or_equal_to: 1
  max_number_of_interactions:
    - is_greater_than_or_equal_to: 1
  emitter_frequency:
    - is_greater_than_or_equal_to: 0
  num_of_pixels:
    - is_greater_than_or_equal_to: 1
  directions:
  timings:
CameraSensorViewConfiguration:
  sensor_id:
  mounting_position:
  mounting_position_rmse:
  field_of_view_horizontal:
  field_of_view_vertical:
  number_of_pixels_horizontal:
    - is_greater_than_or_equal_to: 1
  number_of_pixels_vertical:
    - is_greater_than_or_equal_to: 1
  channel_format:
    - is_greater_than_or_equal_to: 1
  samples_per_pixel:
    - is_greater_than_or_equal_to: 1
  max_number_of_interactions:
    - is_greater_than_or_equal_to: 1
  wavelength_data:
  pixel_order:
UltrasonicSensorViewConfiguration:
  sensor_id:
  mounting_position:
  mounting_position_rmse:
  field_of_view_horizontal:
  field_of_view_vertical:
