SensorViewConfiguration:
  version: any(list(include('rules', required=False)), null(), required=False)
  sensor_id: any(list(include('rules', required=False)), null(), required=False)
  mounting_position: any(list(include('rules', required=False)), null(), required=False)
  mounting_position_rmse: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_horizontal: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_vertical: any(list(include('rules', required=False)), null(), required=False)
  range: any(list(include('rules', required=False)), null(), required=False)
  update_cycle_time: any(list(include('rules', required=False)), null(), required=False)
  update_cycle_offset: any(list(include('rules', required=False)), null(), required=False)
  simulation_start_time: any(list(include('rules', required=False)), null(), required=False)
  omit_static_information: any(list(include('rules', required=False)), null(), required=False)
  generic_sensor_view_configuration: any(list(include('rules', required=False)), null(), required=False)
  radar_sensor_view_configuration: any(list(include('rules', required=False)), null(), required=False)
  lidar_sensor_view_configuration: any(list(include('rules', required=False)), null(), required=False)
  camera_sensor_view_configuration: any(list(include('rules', required=False)), null(), required=False)
  ultrasonic_sensor_view_configuration: any(list(include('rules', required=False)), null(), required=False)
GenericSensorViewConfiguration:
  sensor_id: any(list(include('rules', required=False)), null(), required=False)
  mounting_position: any(list(include('rules', required=False)), null(), required=False)
  mounting_position_rmse: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_horizontal: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_vertical: any(list(include('rules', required=False)), null(), required=False)
RadarSensorViewConfiguration:
  sensor_id: any(list(include('rules', required=False)), null(), required=False)
  mounting_position: any(list(include('rules', required=False)), null(), required=False)
  mounting_position_rmse: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_horizontal: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_vertical: any(list(include('rules', required=False)), null(), required=False)
  number_of_rays_horizontal: any(list(include('rules', required=False)), null(), required=False)
  number_of_rays_vertical: any(list(include('rules', required=False)), null(), required=False)
  max_number_of_interactions: any(list(include('rules', required=False)), null(), required=False)
  emitter_frequency: any(list(include('rules', required=False)), null(), required=False)
  tx_antenna_diagram: any(list(include('rules', required=False)), null(), required=False)
  rx_antenna_diagram: any(list(include('rules', required=False)), null(), required=False)
  AntennaDiagramEntry:
    horizontal_angle: any(list(include('rules', required=False)), null(), required=False)
    vertical_angle: any(list(include('rules', required=False)), null(), required=False)
    response: any(list(include('rules', required=False)), null(), required=False)
LidarSensorViewConfiguration:
  sensor_id: any(list(include('rules', required=False)), null(), required=False)
  mounting_position: any(list(include('rules', required=False)), null(), required=False)
  mounting_position_rmse: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_horizontal: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_vertical: any(list(include('rules', required=False)), null(), required=False)
  number_of_rays_horizontal: any(list(include('rules', required=False)), null(), required=False)
  number_of_rays_vertical: any(list(include('rules', required=False)), null(), required=False)
  max_number_of_interactions: any(list(include('rules', required=False)), null(), required=False)
  emitter_frequency: any(list(include('rules', required=False)), null(), required=False)
  num_of_pixels: any(list(include('rules', required=False)), null(), required=False)
  directions: any(list(include('rules', required=False)), null(), required=False)
  timings: any(list(include('rules', required=False)), null(), required=False)
CameraSensorViewConfiguration:
  sensor_id: any(list(include('rules', required=False)), null(), required=False)
  mounting_position: any(list(include('rules', required=False)), null(), required=False)
  mounting_position_rmse: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_horizontal: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_vertical: any(list(include('rules', required=False)), null(), required=False)
  number_of_pixels_horizontal: any(list(include('rules', required=False)), null(), required=False)
  number_of_pixels_vertical: any(list(include('rules', required=False)), null(), required=False)
  channel_format: any(list(include('rules', required=False)), null(), required=False)
  samples_per_pixel: any(list(include('rules', required=False)), null(), required=False)
  max_number_of_interactions: any(list(include('rules', required=False)), null(), required=False)
  wavelength_data: any(list(include('rules', required=False)), null(), required=False)
  pixel_order: any(list(include('rules', required=False)), null(), required=False)
UltrasonicSensorViewConfiguration:
  sensor_id: any(list(include('rules', required=False)), null(), required=False)
  mounting_position: any(list(include('rules', required=False)), null(), required=False)
  mounting_position_rmse: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_horizontal: any(list(include('rules', required=False)), null(), required=False)
  field_of_view_vertical: any(list(include('rules', required=False)), null(), required=False)
---
rules:
  is_greater_than: num(required=False)
  is_greater_than_or_equal_to: num(required=False)
  is_less_than_or_equal_to: num(required=False)
  is_less_than: num(required=False)
  is_equal_to: any(num(), bool(), required=False)
  is_different_to: num(required=False)
  is_globally_unique: str(required=False)
  refers_to: str(required=False)
  is_iso_country_code: str(required=False)
  is_set: str(required=False)
  check_if: list(include('rules', required=False),required=False)
  do_check: any(required=False)
  target: any(required=False)
  first_element: any(required=False)
  last_element: any(required=False)