on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_model:
    name: Build Model
    uses: openMSL/sl-1-3-object-based-generic-perception-object-model/.github/workflows/build.yml@tracefile_runner

  cpp-linter:
    name: C++ Linter
    uses: openMSL/sl-1-3-object-based-generic-perception-object-model/.github/workflows/cpp-linter.yml@tracefile_runner