name: Credibility Assessment Level 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_model:
    name: Build Model
    uses: openMSL/sl-1-3-object-based-generic-perception-object-model/.github/workflows/build.yml@main

  cpp-linter:
    name: C++ Linter
    uses: openMSL/sl-1-3-object-based-generic-perception-object-model/.github/workflows/cpp-linter.yml@main
    
  markdown-linter:
    name: Markdown Linter
    uses: openMSL/sl-1-3-object-based-generic-perception-object-model/.github/workflows/markdown.yml@main
