name: Archive built FMU as artifact

on:
  workflow_call:

jobs:
  fmu-artifact:
    name: FMU Artifact
    runs-on: ubuntu-latest

    steps:
    - name: Cache Model FMU
      id: cache-model-fmu
      uses: actions/cache@v4
      with:
        path: /tmp/model_fmu
        key: ${{ runner.os }}-model-fmu-${{ github.sha }}

    - name: Archive built FMU
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: /tmp/model_fmu/${{ github.event.repository.name }}.fmu
