name: Tracefile Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_model:
    name: Build Model FMU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Model
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Cache Dependencies
      id: cache-depends
      uses: actions/cache@v3
      with:
        path: protobuf-21.12
        key: ${{ runner.os }}-v1-depends

    - name: Download ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.tar.gz && tar xzvf protobuf-all-21.12.tar.gz

    - name: Build ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      working-directory: protobuf-21.12
      run: ./configure DIST_LANG=cpp --disable-shared CXXFLAGS="-fPIC" && make

    - name: Install ProtoBuf
      working-directory: protobuf-21.12
      run: sudo make install && sudo ldconfig

    - name: Prepare C++ Build
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: cmake -DCMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install ..

    - name: Build C++
      working-directory: build
      run: cmake --build .
      
    - name: Create FMU Directory
      working-directory: build
      run: mkdir /tmp/model_fmu
      
    - name: Copy Model FMU
      working-directory: build
      run: cp ObjectBasedGenericPerceptionObjectModel.fmu /tmp/model_fmu/ObjectBasedGenericPerceptionObjectModel.fmu

    - name: Cache Model FMU
      id: cache-model-fmu
      uses: actions/cache@v3
      with:
        path: /tmp/model_fmu
        key: ${{ runner.os }}-model-fmu

  build_tracefile_player:
    name: Build Tracefile Player FMU
    runs-on: ubuntu-latest

    steps:
    - name: Cache Dependencies
      id: cache-depends
      uses: actions/cache@v3
      with:
        path: protobuf-21.12
        key: ${{ runner.os }}-v1-depends

    - name: Download ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.tar.gz && tar xzvf protobuf-all-21.12.tar.gz

    - name: Build ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      working-directory: protobuf-21.12
      run: ./configure DIST_LANG=cpp --disable-shared CXXFLAGS="-fPIC" && make

    - name: Install ProtoBuf
      working-directory: protobuf-21.12
      run: sudo make install && sudo ldconfig

    - name: Get Tracefile Player
      run: git clone https://gitlab.com/persival-open-source/open-simulation-interface/osi-trace-file-player.git

    - name: Prepare C++ Build
      working-directory: osi-trace-file-player
      run: git submodule update --init && mkdir build

    - name: Configure CMake
      working-directory: osi-trace-file-player/build
      run: cmake -DCMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install ..

    - name: Build C++
      working-directory: osi-trace-file-player/build
      run: cmake --build .
      
    - name: Create FMU Directory
      working-directory: osi-trace-file-player/build
      run: mkdir /tmp/tracefile_fmu

    - name: Copy Tracefile FMU
      working-directory: osi-trace-file-player/build
      run: cp src/OSMPTraceFilePlayer.fmu /tmp/tracefile_fmu/OSMPTraceFilePlayer.fmu

    - name: Cache Tracefile FMU
      id: cache-tracefile-fmu
      uses: actions/cache@v3
      with:
        path: /tmp/tracefile_fmu
        key: ${{ runner.os }}-tracefile-fmu

  build_evaluation_fmu:
    name: Build Evaluation FMU
    runs-on: ubuntu-latest

    steps:
      - name: Cache Dependencies
        id: cache-depends
        uses: actions/cache@v3
        with:
          path: protobuf-21.12
          key: ${{ runner.os }}-v1-depends

      - name: Download ProtoBuf
        if: steps.cache-depends.outputs.cache-hit != 'true'
        run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.tar.gz && tar xzvf protobuf-all-21.12.tar.gz

      - name: Build ProtoBuf
        if: steps.cache-depends.outputs.cache-hit != 'true'
        working-directory: protobuf-21.12
        run: ./configure DIST_LANG=cpp --disable-shared CXXFLAGS="-fPIC" && make

      - name: Install ProtoBuf
        working-directory: protobuf-21.12
        run: sudo make install && sudo ldconfig

      - name: Get Evaluation FMU
        run: git clone https://github.com/Persival-GmbH/osi-check-fmu.git

      - name: Prepare C++ Build
        working-directory: osi-check-fmu
        run: git submodule update --init && mkdir build

      - name: Configure CMake
        working-directory: osi-check-fmu/build
        run: cmake -DCMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install ..

      - name: Build C++
        working-directory: osi-check-fmu/build
        run: cmake --build .

      - name: Create FMU Directory
        working-directory: osi-check-fmu/build
        run: mkdir /tmp/evaluation_fmu

      - name: Copy Evaluation FMU
        working-directory: osi-check-fmu/build
        run: cp OSICheck.fmu /tmp/evaluation_fmu/OSICheck.fmu

      - name: Cache Evaluation FMU
        id: cache-evaluation-fmu
        uses: actions/cache@v3
        with:
          path: /tmp/evaluation_fmu
          key: ${{ runner.os }}-evaluation-fmu

  test:
    needs: [build_model, build_tracefile_player, build_evaluation_fmu]
    name: Run Model FMU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Model
      uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Cache Model FMU
      id: cache-model-fmu
      uses: actions/cache@v3
      with:
        path: /tmp/model_fmu
        key: ${{ runner.os }}-model-fmu

    - name: Cache Tracefile FMU
      id: cache-tracefile-fmu
      uses: actions/cache@v3
      with:
        path: /tmp/tracefile_fmu
        key: ${{ runner.os }}-tracefile-fmu

    - name: Cache Tracefile
      id: cache-tracefile
      uses: actions/cache@v3
      with:
        path: /tmp/osi
        key: ${{ runner.os }}-tracefile
    
    - name: Create Tracefile Directory
      run: mkdir /tmp/osi
      
    - name: Copy Tracefile
      run: cp .github/workflows/tracefile_analysis/20230221T153730Z_sv_340_300_0000_protoBin.osi /tmp/osi/20230221T153730Z_sv_340_300_0000_protoBin.osi

    - name: Cache Evaluation FMU
      id: cache-evaluation-fmu
      uses: actions/cache@v3
      with:
        path: /tmp/evaluation_fmu
        key: ${{ runner.os }}-evaluation-fmu

    - name: Copy OSI Check File
      run: cp .github/workflows/tracefile_analysis/osi_check.txt /tmp/osi_check.txt

    - name: Install dependencies
      run: sudo apt install -y libxml2-dev zlib1g-dev libzip-dev
        
    - name: Get OpenMCx
      run: git clone https://github.com/eclipse/openmcx.git
      
    - name: Build OpenMCx
      working-directory: openmcx
      run: ./build.sh
      
    - name: Run OpenMCx
      id: cosimulation
      working-directory: openmcx
      run: ./install/openmcx ../.github/workflows/tracefile_analysis/Tracefile_ObjectBased_Evaluation.ssd
      
    - name: Test Fail criterion
      run: echo "Fail output is ${{ steps.cosimulation.outputs.num_missing_fields }}"  
      
    - name: Failed?
      if: steps.cosimulation.outputs.num_missing_fields>0
      run: exit 1


