name: Tracefile Analysis

on:
  push:
    branches: [ "tracefile_runner" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_model:
    name: Build Model FMU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Model
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Cache Dependencies
      id: cache-depends
      uses: actions/cache@v2
      with:
        path: protobuf-21.12
        key: ${{ runner.os }}-v1-depends

    - name: Download ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.tar.gz && tar xzvf protobuf-all-21.12.tar.gz

    - name: Build ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      working-directory: protobuf-21.12
      run: ./configure DIST_LANG=cpp --prefix=/usr --disable-shared CXXFLAGS="-fPIC" && make

    - name: Install ProtoBuf
      working-directory: protobuf-21.12
      run: sudo make install && sudo ldconfig

    - name: Prepare C++ Build
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: cmake -DCMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install ..

    - name: Build C++
      working-directory: build
      run: cmake --build .
      
    - name: Create FMU Directory
      working-directory: build
      run: mkdir /tmp/model_fmu
      
    - name: Copy Model FMU
      working-directory: build
      run: cp ObjectBasedGenericPerceptionObjectModel.fmu /tmp/model_fmu/ObjectBasedGenericPerceptionObjectModel.fmu

    - name: Cache Model FMU
      id: cache-model-fmu
      uses: actions/cache@v2
      with:
        path: /tmp/model_fmu
        key: ${{ runner.os }}-model-fmu

  build_tracefile_player:
    name: Build Tracefile Player FMU
    runs-on: ubuntu-latest

    steps:
    - name: Cache Dependencies
      id: cache-depends
      uses: actions/cache@v2
      with:
        path: protobuf-21.12
        key: ${{ runner.os }}-v1-depends

    - name: Download ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.tar.gz && tar xzvf protobuf-all-21.12.tar.gz

    - name: Build ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      working-directory: protobuf-21.12
      run: ./configure DIST_LANG=cpp --prefix=/usr --disable-shared CXXFLAGS="-fPIC" && make

    - name: Install ProtoBuf
      working-directory: protobuf-21.12
      run: sudo make install && sudo ldconfig

    - name: Get Tracefile Player
      run: git clone https://gitlab.com/persival-open-source/open-simulation-interface/osi-trace-file-player.git

    - name: Prepare C++ Build
      working-directory: osi-trace-file-player
      run: git submodule update --init && mkdir build

    - name: Configure CMake
      working-directory: osi-trace-file-player/build
      run: cmake -DCMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install ..

    - name: Build C++
      working-directory: osi-trace-file-player/build
      run: cmake --build .
      
    - name: Create FMU Directory
      working-directory: osi-trace-file-player/build
      run: mkdir /tmp/tracefile_fmu
      
    - name: Copy Tracefile FMU
      working-directory: osi-trace-file-player/build
      run: cp src/OSMPTraceFilePlayer.fmu /tmp/tracefile_fmu/OSMPTraceFilePlayer.fmu

    - name: Cache Tracefile FMU
      id: cache-tracefile-fmu
      uses: actions/cache@v2
      with:
        path: /tmp/tracefile_fmu
        key: ${{ runner.os }}-tracefile-fmu

  test:
    needs: [build_model, build_tracefile_player]
    name: Run Model FMU
    runs-on: ubuntu-latest

    steps:
    - name: Cache Model FMU
      id: cache-model-fmu
      uses: actions/cache@v2
      with:
        path: /tmp/fmus
        key: ${{ runner.os }}-model-fmu
    - name: Cache Tracefile FMU
      id: cache-tracefile-fmu
      uses: actions/cache@v2
      with:
        path: /tmp/tracefile_fmu
        key: ${{ runner.os }}-tracefile-fmu
    - name: Check Model FMU
      if: steps.cache-model-fmu.outputs.cache-hit != 'true'
      working-directory: /tmp/fmus
      run: ls -1


